name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - id: version
        run: |
          NEXT_RELEASE=$(date "+%Y.%-m.%-d")
          LAST_RELEASE=$(git tag --sort=v:refname | grep "^20[^-]*$" | tail -n 1)
          MAJOR_LAST_RELEASE=$(echo "${LAST_RELEASE}" | awk -v l=${#NEXT_RELEASE} '{ string=substr($0, 1, l); print string; }')
          if [ "${MAJOR_LAST_RELEASE}" = "${NEXT_RELEASE}" ]; then
            MINOR_LAST_RELEASE=$(echo "${LAST_RELEASE}" | awk -v l=$(expr ${#NEXT_RELEASE} + 2) '{ string=substr($0, l); print string; }')
            NEXT_RELEASE=${MAJOR_LAST_RELEASE}.$((MINOR_LAST_RELEASE + 1))
          fi
          echo "VERSION=$NEXT_RELEASE" >> $GITHUB_OUTPUT

      - run: git tag ${{ steps.version.outputs.VERSION }}

      - run: git push origin ${{ steps.version.outputs.VERSION }}

      - run: npm install

      - run: npm run build

      - run: npm run bundle

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          files: dist/scip-typescript.cjs
